name: Auto Sync

on:
  schedule:
    - cron: "*/5 * * * *" # At 00:00.  https://crontab.guru/
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: vitest-dev/vitest
          upstream_branch: main
          target_repository: elonehoo/vitest-docs-template
          target_branch: upstream
          force: false
          tags: false
